---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  username: ubuntu
  flavor_id: c3.large
  interface: public

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver_config:
      image_id: ami-36aa4d5e
      tags:
        Name: travis-ci-default-ubuntu-1204
        Env: public
  - name: debian-7.6
    driver_config:
      image_id: ami-f4ad649c
      tags:
        Name: travis-ci-default-debian-7.6
        Env: public

suites:
  - name: default
    run_list:
      - recipe[archiva::nginx_proxy]
