language: ruby
rvm:
- 1.9.3
before_install:
- mkdir ~/.ssh
- openssl aes-256-cbc -K $encrypted_755628117be5_key -iv $encrypted_755628117be5_iv
  -in travis_ci_ec2.pem.enc -out ~\/.ssh/travis_ci_ec2.pem -d
- chmod 600 ~/.ssh/travis_ci_ec2.pem
install:
- bundle install --without vagrant
- bundle exec berks install
script:
- bundle exec rake travis
after_script:
- bundle exec rake integration:cloud_destroy
notifications:
  slack:
    secure: IrLfd/b0zFqRn+9Ny1besU3tM804y7zJIoWX5XHX0M8y94V807gAyKKhS2A+AB2Xaysax1FVO5b1FShCyv1P08GJE0PsgxzNj8XjunqR4A6xYHVekJRRImeTjBKlzCC3NU8+2WShenbloU6un/QzTII/HG6FYL/cMtUgtlfsvNY=
env:
  global:
  - secure: OtJYkBCPm7eaep3w1vgdwWqonn5xVmeqtwwBvCEslSyvhF7cBGu9+a02QXnJfTgRQj3ieEtWSMZZcAf8Y3GPH87wHC13OHyaDDGfUK0jCeX9V+NoYRHdIk0wYYEoHaF3kXJKjlYMWuvu4QH1GBTCgkDm1hFfFCmjVqa947CGivU=
  - secure: NdO5gS25mkESaA8/OLKlqtxIqZ/LQchL0/xfw9dDBCIpFDYNVNNRru68o2Y3QxDAOqmRzsK6DhYrCbd0rieH37tokEmLgT1iIVIARijU2nVHIqY65QZGPm1Ck0jn9xabx/OxXFIDkSd6AFodns7XSGsiSTpwuLMtrDRwCG4Q5Gc=
  - secure: eBEVYTVyIX14gP50TvKt1MFahj36TULu4QLqVBhpYsTp+SMN5/IOUnPojJJHVN+Bsz1ma/Z4hGDWa+nXLsclK+ZHLLL8PuyDXKMMcfzzH07T/0AzICYZSCUAjoSVF/j6viVJ71eKAEnhbyzyus/C9bywRs2wkMy6dpMY4mduQ3U=
  - secure: Jnhw2t4rQV+dln4erEGYtguneqa8UOkEOc5MpugQmLhfpBy9YebK5ut+D3NqUCqCR08c8NWDKEvz+xfC6Skzv+hL+8jccGEoiIHYbBUqvi9hCoYEUC06F2fQjPwajqWYHTABi6ZEV40zS3hd5vy2fGxP8PTw6LdXGsPpIL+MZf4=
